#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-local-lib
Version  : 2.000024
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/H/HA/HAARG/local-lib-2.000024.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/H/HA/HAARG/local-lib-2.000024.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libl/liblocal-lib-perl/liblocal-lib-perl_2.000024-1.debian.tar.xz
Summary  : 'create and use a local lib/ for perl modules with PERL5LIB'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-local-lib-license
Requires: perl-local-lib-man

%description
NAME
local::lib - create and use a local lib/ for perl modules with PERL5LIB
SYNOPSIS
In code -

%package license
Summary: license components for the perl-local-lib package.
Group: Default

%description license
license components for the perl-local-lib package.


%package man
Summary: man components for the perl-local-lib package.
Group: Default

%description man
man components for the perl-local-lib package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n local-lib-2.000024
mkdir -p %{_topdir}/BUILD/local-lib-2.000024/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/local-lib-2.000024/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-local-lib
cp LICENSE %{buildroot}/usr/share/doc/perl-local-lib/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/POD2/DE/local/lib.pod
/usr/lib/perl5/site_perl/5.26.1/POD2/PT_BR/local/lib.pod
/usr/lib/perl5/site_perl/5.26.1/lib/core/only.pm
/usr/lib/perl5/site_perl/5.26.1/local/lib.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-local-lib/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/POD2::DE::local::lib.3
/usr/share/man/man3/POD2::PT_BR::local::lib.3
/usr/share/man/man3/lib::core::only.3
/usr/share/man/man3/local::lib.3
